version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: todo_app
        restart: unless-stopped
        ports:
            - "8000:8000"
        # volumes:
        #     - .:/var/www/html
        depends_on:
            - mysql
        networks:
            - todo_app_network

    mysql:
        image: mysql:8.0
        container_name: mysql
        environment:
            MYSQL_DATABASE: elecard
            MYSQL_ROOT_PASSWORD: 123456789
        ports:
            - "3307:3306"
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - todo_app_network

    # стоило бы добавить nginx

networks:
    todo_app_network:
        driver: bridge

volumes:
    mysql-data:
